# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GS-APOD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GS-APOD
  pod 'SDWebImage', '~> 5.0'

  target 'GS-APODTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GS-APODUITests' do
    # Pods for testing
  end

end
